namespace Parser.AST
{
    enum IntermediateNodeType
    {
        Program,
        ClassList,
        FuncDefList,
        ClassDecl,
        FuncDef,
        InheritList,
        MemberList,
        VarDecl,
        FuncDecl,
        FParam,
        FParamList,
        DimList,
        StatBlock,
        IfStat,
        AssignStat,
        ForStat,
        GetStat,
        PutStat,
        ReturnStat,
        AddOp,
        RelExpr,
        MultOp,
        Not,
        Sign,
        Var,
        DataMember,
        FCall,
        IndexList,
        AParams
    }
}
